-- 1.Install addin for MySQL for MS Excel.
-- Installed
-- 2.Access Schema sakila through MS Excel.
-- got access
-- 3.Import data from table customer, actor, film_category, inventory into MS Excel with pivottable and data summary.
-- imported
-- 4.Do insertion of new 10 rows in table film_text through MS Excel.
-- inserted
-- 5.Append data of table rental through MS Excel with 5 rows.
-- solved
-- 6.Export data of view customer_list (rows where value of field notes is NULL) into  newcustomer_list through MS Excel
-- exported..
-- refer excel file 